### PR TITLE
:fire: Added flag `--force`

### PR DESCRIPTION
**Pull request by RaschidJFR**
* `--force` flag will delete target database before copying from the source
* Fixed minor issue: main() not resolving/rejecting promise
* Created CHANGELOG.md

### CODE REVIEW

**Comment by RaschidJFR** [comment]
Hey @fr1sk great job. I've just added an option to address the `E11000 duplicate key error`. Hope you like it.

**Comment by fr1sk** [comment]
Hi @RaschidJFR and thanks for contributing 🍻force feature is great, good job on that one 👍🏻Also sorry for not approving you PR faster, I was on vacation.

If you have some other ideas in the future, feel free to contact me and we can develop them together.

Enjoy 🎉

**Comment by RaschidJFR** [comment]
Hey @fr1sk don't forget to publish this new version! ;)

**Comment by fr1sk** [comment]
@RaschidJFR New version is published, sorry for the delay :)

**Pull request merged**
